#! $ docker-compose up --build

version: "3"
services:
  server: # define the name of the container
    build:
      context: ./server/ # specify the location of the docker file
    command: npm run dev # command that is run after the build is complete
    volumes: # specifu location of volumes
      - ./server/:/usr/app
      - /usr/app/node_modules
    ports: # specify the ports I want to expose and where to
      - "5000:5000"
    env_file: ./server/.env # specify location of .env file
    links: # specify the connection to mongo database
      - mongo
  client:
    build:
      context: ./client/
    command: npm start
    volumes:
      - ./client/:/usr/app
      - /usr/app/node_modules
    links: # specify connection to the server
      - server
    ports:
      - "3000:3000"
  mongo:
    container_name: mongo_alteos_db
    image: mongo # specify the image to be downloaded from dockerhub
    ports:
      - "27017:27017"
